# Generated by Django 3.1.3 on 2020-11-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='origin_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
