# Generated by Django 3.1.3 on 2020-11-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processing', '0002_auto_20201128_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='origin_file',
        ),
        migrations.AddField(
            model_name='file',
            name='origin_mime',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='file',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
