# Generated by Django 3.1.3 on 2020-11-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processing', '0003_auto_20201128_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='processed_file',
            field=models.FileField(null=True, upload_to='processed'),
        ),
        migrations.AlterField(
            model_name='file',
            name='origin_file',
            field=models.FileField(null=True, upload_to='origins'),
        ),
        migrations.AlterField(
            model_name='file',
            name='processed_text',
            field=models.TextField(null=True),
        ),
    ]
