# Generated by Django 3.1.3 on 2020-11-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processing', '0004_auto_20201128_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='input_type',
            field=models.CharField(blank=True, choices=[('docx', 'Docx'), ('txt', 'Txt'), ('image', 'Image'), ('pdf', 'Pdf')], default='', max_length=50),
        ),
    ]
