# Generated by Django 3.1.3 on 2020-11-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processing', '0006_auto_20201129_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='processed_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
