# Generated by Django 3.1.3 on 2020-11-29 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_processing', '0007_auto_20201129_0244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TextboxUnit',
        ),
    ]
